name: api-deploy-img-aci

trigger:
 branches:
  include:
  - master
 paths:
  include:
  - FoodUI/*

variables:
  env: dev
  img: arambazamba/foodui
  dns: foodui
  azSubs: az400-m015

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "Deploy"
    displayName: "Deploy Img"
    jobs:
      - job: "Deploy"
        steps:
        
        - task: AzureCLI@2
          displayName: 'Deploy Img to ACI'
          inputs:
            azureSubscription: '$(azSubs)'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: '$(System.DefaultWorkingDirectory)/food-app/az-cli/create-container-instance.sh'
            arguments: $(env) $(img) $(dns)
