name: catalog-api-cicd-gates

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - food-api

trigger: none
pr: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: conFood
  path: apps/catalog-api/api/
  appservice: food-catalog-api-prod

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build

        steps:
          - task: UseDotNet@2
            displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
            inputs:
              version: "$(dotnetSdkVersion)"

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "$(path)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "$(path)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Publish the project - $(buildConfiguration)"
            inputs:
              command: "publish"
              projects: "$(path)/*.csproj"
              publishWebProjects: false
              arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
              zipAfterPublish: true

          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: apidrop
            displayName: "Publish Artifact: apidrop"

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to prod Appservice
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifact: apidrop
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azSubscription)
                    appType: "webApp"
                    WebAppName: "$(appservice)-$(envflag)"
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
