name: spfx-build-deploy

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - "*"
#     exclude:
#       - az-pipelines/*
#       - _images/*

trigger: none

variables:
  nodeVersion: "14.x"
  sppkg: foodlist-wp.sppkg
  fld: food-spfx-wp
  # set pipeline vars: username, password

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: Build SPFx
        steps:
          - template: templates/t-spfx-build.yaml
            parameters:
              nodeVersion: $(nodeVersion)
              pkg: $(sppkg)

  - stage: Deploy
    displayName: Deploy to M365
    dependsOn: Build
    jobs:
      - deployment: DeployM365
        displayName: Deploy to M365
        environment: M365Prod
        strategy:
          runOnce:
            deploy:
              steps:            
                - template: templates/t-spfx-deploy-cli.yaml
                  parameters:
                    nodeVersion: $(nodeVersion)
                    pkg: $(sppkg)
                    username: $(username)
                    password: $(password)