name: .Net Core Api AppService

on:
  push:
    branches:
      - master
    paths:
      - "FoodApi/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Build with dotnet
        run: dotnet build ${{ github.workspace }}/FoodApi/FoodApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ github.workspace }}/FoodApi/FoodApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/api
              
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: foodapi-githubaction-900
          publish-profile: ${{ secrets.FOODAPIPROFILE }}
          package: ${{env.DOTNET_ROOT}}/api
