name: catalog api ci/cd

on:
  push:
    branches:
      - master
    paths:
      - "food-api/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true       

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Build with dotnet
        run: dotnet build ${{ github.workspace }}/food-api/food-api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ github.workspace }}/food-api/food-api.csproj -c Release -o ${{env.DOTNET_ROOT}}/api
                        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: foodapi-github-actions
          slot-name: PRODUCTION
          publish-profile: ${{ secrets.FOODAPIPROFILE }}
          package: ${{env.DOTNET_ROOT}}/api
