name: Export Issues to Azure DevOps Boards
on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issues to Azure DevOps
        uses: danhellem/github-actions-issue-to-work-item@v2.0
        env:
          ado_token: "${{ secrets.ADO_SYNC_TOKEN }}"
          github_token: "${{ secrets.GH_SYNC_TOKEN }}"
          ado_organization: "integrations-training"
          ado_project: "az-400"
          ado_wit: "Issue"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
