name: api-build-deploy

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - food-api

trigger: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  releaseBranchName: master
  serviceCon: conAzTenant
  apifolder: food-api
  appservice: foodapi-release-strategy

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: "Build"
        displayName: "Build job"

        steps:
          - template: templates/netcore-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(apifolder)
  - stage: Deploy
    displayName: Deploy
    dependsOn: Build

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: $(envflag)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(serviceCon)
                    appType: "webApp"
                    WebAppName: "$(appservice)"
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
