name: FoodApi Docker Build
pool:
  vmImage: "ubuntu-20.04"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - FoodApi/*

variables:
  apiPath: "FoodApi/"
  conACR: "conM15"
  imageName: "foodapi"   

stages:
  - stage: "BuildApi"
    displayName: "Build Api Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(conACR)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: "$(imageName)"
              command: "buildAndPush"
              Dockerfile: "$(apiPath)dockerfile"

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(conACR)
