name: Kubernetes Deploy
pool:
  vmImage: "ubuntu-20.04"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - FoodApi/*

variables:
  conACI: conDockerReg
  conKube: conKube
  acr: integrationsonline.azurecr.io
  img: foodapi
  yml: az-manifests/foodapi.yml
  tag: $(Build.BuildId)
  ns: staging
  imagePullSecret: secret

stages:
  - stage: "BuildApi"
    displayName: "Build Api Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(conACI)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: $(img)
              command: buildAndPush
              Dockerfile: FoodApi/dockerfile
          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(conACI)
          - publish: "$(Build.SourcesDirectory)/manifests"
            artifact: manifests

  - stage: Deploy
    displayName: Deploy stage

    jobs:
      - deployment: Deploy
        displayName: Deploy Job
        environment: "staging.default"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: Create imagePullSecret
                  inputs:
                    action: createSecret
                    secretName: $(imagePullSecret)
                    kubernetesServiceConnection: $(conKube)
                    dockerRegistryEndpoint: $(conACI)
                    namespace: $(ns)

                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    kubernetesServiceConnection: $(conKube)
                    action: "deploy"
                    manifests: |
                      $(Pipeline.Workspace)/$(yml)
                    imagePullSecrets: $(imagePullSecret)
                    containers: "$(acr)/$(img):$(tag)"
