name: api-docker.yml

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - food-api/*

trigger: none      

variables:
  apiPath: "food-api/"
  conACR: "conACR"
  imageName: "foodapi"   

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: "BuildApi"
    displayName: "Build Api Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(conACR)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: "$(imageName)"
              command: "buildAndPush"
              Dockerfile: "$(apiPath)dockerfile"
              tags: $(Build.BuildId)

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(conACR)
