name: Kubernetes Deploy

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - FoodApi/*

trigger: none

variables:
  System.Debug: true
  conACR: conACR
  acr: integrationsonline.azurecr.io
  conKube: conKube
  img: foodapi
  yml: $(Pipeline.Workspace)/s/az-manifests/foodapi.yaml

  tag: $(Build.BuildId)
  ns: staging
  imagePullSecret: secret
  env: foodapp-staging

pool:
  vmImage: "ubuntu-20.04"
  # name: aci-pool  

stages:
  - stage: "Prepare"
    displayName: "Build Api Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(conACR)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: $(img)
              command: buildAndPush
              Dockerfile: food-api/dockerfile
          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(conACR)
          - publish: "$(Build.SourcesDirectory)/manifests"
            artifact: manifests

  - stage: Deploy
    displayName: Deploy stage

    jobs:
      - deployment: Deploy
        displayName: Deploy Job
        environment: $(env)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: KubernetesManifest@0
                  displayName: Create imagePullSecret
                  inputs:
                    action: 'createSecret'
                    kubernetesServiceConnection: 'foodapp-staging-foodcluster-31852-staging-1644620442182'
                    namespace: '$(ns)'
                    secretType: 'dockerRegistry'
                    secretName: '$(imagePullSecret)'
                    dockerRegistryEndpoint: '$(conACR)'
                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'foodapp-staging-foodcluster-31852-staging-1644620442182'
                    manifests: '$(yml)'
                    containers: '$(acr)/$(img):$(tag)'
                    imagePullSecrets: '$(imagePullSecret)'
