name: ms-build-deploy-cli

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - FoodUI

variables:
  azSubscription: az400-mod13-subscription
  uiPath: FoodUI/
  apinumber: '911'
  appservice: 'foodapi'

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build and Provision
    jobs:
      - job: ngBuild

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node 14"

          - script: |
              npm i -g @angular/cli
              npm i
              ng b -c production
            displayName: "npm install and build"
            workingDirectory: $(uiPath)

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "ngdrop"
              publishLocation: "Container"
      
      - job: Provision

        steps:
        
        - task: AzureCLI@2
          displayName: 'Provision AppService'
          inputs:
            azureSubscription: '$(azSubscription)'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: '$(System.DefaultWorkingDirectory)/az-cli/create-ui-webapp.sh'
            arguments: '$(apinumber)'

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "ngdrop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azSubscription)
                    appType: "webApp"
                    WebAppName: "$(appservice)-$(apinumber)"
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
